### ISSUE TITLE
ENH: Prepare for fbo.gov decomission

### ISSUE THREAD

**Issue by csmcallister** [GSA/srt-fbo-scraper#142]
## Expected Behavior
When fbo.gov is decommissioned and we can no longer rely on their FTP server to get data, we need the app to gracefully switch to getting the data from beta.sam.gov.

## Current Behavior
Data is only scraped from fbo's FTP server

## Possible Solution
Web-scrape contract opportunities from beta.sam.gov. This data is probably not relying on the same FTP server, so it might be in an easier-to-use data store where we could collaborate with FAS to access without the need for web-scraping.

## Context
SRT depends on having access to this data. With fbo.gov being decommissioned, we need to find a replacement data source.

**Comment by csmcallister** [comment]
I've starting working on this in a local branch. Will push to track soon.

**Comment by joshchuable** [comment]
Hi! Do you have context on this? Is the FBO FTP server getting decommissioned?

**Comment by csmcallister** [comment]
Hi @joshchuable! I heard about this from a colleague in IT here at GSA and then confirmed it with some googling. This [page](https://interact.gsa.gov/blog/iae-and-betasamgov-modernization-update), for example, says the decommissioning will happen at some point in FY2020. I'm not 100% sure, however, what's going to happen to the FBO FTP server. For the purposes of this project, I'm assuming a worst-case-scenario (i.e. that it goes away) and so I'm working on using the FBO replacement (beta.sam.gov). 

Sorry I can't shed more light upon this. I work in GSA's Office of Government-wide Policy, which is separate from the Federal Acquisition Service, which runs the [Federal Service Desk](https://www.fsd.gov/fsd-gov/home.do). They're the ones that manage FBO and related systems. They have contact info on their site and are generally pretty good at answering questions.

**Comment by csmcallister** [comment]
FBO.gov will sunset on 11/8/19. I emailed the beta.sam team on Tue, Sep 3 to ask about their preferred method for our system to access opportunities data. Once we hear back from them, we can proceed with this migration.

**Comment by marcborbely** [comment]
Hi, any update on this? The company I work for uses the daily XML feeds too. The ftp site (ftp://ftp.fbo.gov) appears to be down. Any idea whether the feeds are available somewhere else?

**Comment by joshchuable** [comment]
@marcborbely I believe you can still download the FBO files here https://beta.sam.gov/data-services?domain=Contract%20Opportunities%2Fdaily%2Fhistorical. I haven't seen the last two days pop up, so not sure if they've stopped those, too.


@csmcallister, I tried to make a few requests similar to how you do in your SAM branch. I am using an API key that I generated on https://gsa.github.io/sam_api/sam/key. I get the error "An invalid API key was supplied. Please submit with a valid API key." Am I missing something?

**Comment by marcborbely** [comment]
Thank you. I also haven’t found the most recent data. I did get the following response from the Federal Service Desk, via e-mail today:

 

The files available in FBO's FTP service are no longer supported in  <http://beta.sam.gov/> beta.SAM.gov. You may find the same data in the following formats:

*  A Full Nightly Opportunity Notice Data Export from Data Services (replaces FBOFullXML) Full daily file downloads of all active notices in the contract opportunities domain can be found in the 'data services' area of the site either from this direct link ( <https://beta.sam.gov/data-services?domain=none%29.> https://beta.sam.gov/data-services?domain=none).  You may also find data services directly from the  <http://beta.sam.gov/> beta.SAM.gov header. Once in data services, select the contract opportunities folder then the following to get various  <http://beta.sam.gov/> beta.SAM.gov and legacy FBO files:

o    Datagov - Full data export of active opportunities data

o    Archived Data - Archived opportunities data.  Files are by year and updated weekly

o    Daily, FBORecovery, FBORecoveryAwards - legacy FBO files for historical purposes 

*  Public GET API of Notice Data (replaces FBO Feeds) Contract opportunity notices can be requested through the public API at  <https://open.gsa.gov/api/get-opportunities-public-api/> https://open.gsa.gov/api/get-opportunities-public-api/. You should obtain an API key prior to accessing the API.  You will be able to obtain an API key from your user profile found in your workspace on  <http://beta.sam.gov/> beta.SAM.gov.

**Comment by marcborbely** [comment]
Thank you! I also haven’t found the most recent data. I did get the following response from the Federal Service Desk, via e-mail today, and was able to generate an API key through my new login.gov account. The API key seems to work, but couldn’t return any recent data either.

 

----------------

The files available in FBO's FTP service are no longer supported in  <http://beta.sam.gov/> beta.SAM.gov. You may find the same data in the following formats:

*  A Full Nightly Opportunity Notice Data Export from Data Services (replaces FBOFullXML) Full daily file downloads of all active notices in the contract opportunities domain can be found in the 'data services' area of the site either from this direct link ( <https://beta.sam.gov/data-services?domain=none%29.> https://beta.sam.gov/data-services?domain=none).  You may also find data services directly from the  <http://beta.sam.gov/> beta.SAM.gov header. Once in data services, select the contract opportunities folder then the following to get various  <http://beta.sam.gov/> beta.SAM.gov and legacy FBO files:

o    Datagov - Full data export of active opportunities data

o    Archived Data - Archived opportunities data.  Files are by year and updated weekly

o    Daily, FBORecovery, FBORecoveryAwards - legacy FBO files for historical purposes 

*  Public GET API of Notice Data (replaces FBO Feeds) Contract opportunity notices can be requested through the public API at  <https://open.gsa.gov/api/get-opportunities-public-api/> https://open.gsa.gov/api/get-opportunities-public-api/. You should obtain an API key prior to accessing the API.  You will be able to obtain an API key from your user profile found in your workspace on  <http://beta.sam.gov/> beta.SAM.gov.

**Comment by dails08** [comment]
The beta SAM site looks like it provides a good rest endpoint for this.

https://open.gsa.gov/api/get-opportunities-public-api/

**Comment by albertcrowley** [comment]
This has been resolved. Scraper now pulls data from a few sam.gov API calls. Closing issue.
